#pragma once

// Generated by tools/swfgen/build.py - do not edit.

namespace StarfrostWidgets::Skin
{
	inline constexpr const char* kMovieName = "StarfrostWidgets";

	inline constexpr std::size_t kFillSteps = 100;
	inline constexpr std::size_t kCaptionSlots = 8;
	inline constexpr float       kGlyphCell = 56.0f;
	inline constexpr float       kGlyphHeight = 100.0f;
	inline constexpr const char* kGlyphOrder = " 0123456789:hms/";

	inline constexpr float kRingArtRadius = 100.0f;
	inline constexpr float kIconArtRadius = 100.0f;
	inline constexpr float kBarArtWidth = 190.0f;
	inline constexpr float kBarArtHeight = 46.0f;
	inline constexpr float kBadgeArtRadius = 100.0f;

	inline constexpr const char* kGaugeClips[] = {
		"sfw_hunger",
		"sfw_sleep",
		"sfw_injury",
		"sfw_cold",
		"sfw_food",
		"sfw_alcohol",
		"sfw_blessing",
		"sfw_stress",
		"sfw_lute",
	};
}
